"use client";

import React from "react";
import TextPage from "@/app/ui/components/TextPage";

export default function Comunicato() {
  const mainColor = "green";
  const secondaryColor = "lime"

  const title = "Comunicato stampa"
  const subtitle = "Il 5 settembre Brescia Pride torna in piazza e porta al Comune tre proposte di politiche pubbliche per la città"

  const subtitleClassName = `font-bold text-2xl mt-2 text-${mainColor}`;
  const textClassName = "mt-2 text-lg";

  const content = (
    <div>
      <p className={textClassName}>
        <em>Carriera Alias in Comune, un catalogo di percorsi educativi per le scuole e uno spazio civico per la comunità LGBTQIA+: dialogo già aperto con la Sindaca.</em> <em>La settima edizione si terrà a Campo Marte, con corteo dalle 15:30.</em>
      </p>
      <p className={textClassName}><b>BRESCIA, 1 settembre 2026 - Brescia Pride</b> torna in piazza sabato <b>5 settembre</b> con la sua <b>settima edizione</b>: una giornata di iniziative nel <b>Parco</b> <b>Campo Marte</b> e un corteo attraverso le vie cittadine, sotto lo slogan <b>«Esistiamo ovunque, resistiamo unit3»</b>.
      </p><p className={textClassName}>pIl Comitato sceglie di accompagnare la manifestazione con un annuncio che guarda oltre la singola giornata: la proposta, già presentata alla Sindaca Laura Castelletti, di avviare con il Comune di Brescia un percorso stabile di collaborazione su tre priorità concrete per la città.</p>
      <p className={textClassName}>In un momento in cui, in Italia e in Europa, i diritti delle persone LGBTQIA+ sono costantemente rimessi in discussione nel dibattito pubblico e nelle scelte politiche, il Pride bresciano riafferma la propria <b>identità intersezionale, transfemminista, antirazzista e antifascista</b>, ribadendo che il corteo è solo l&apos;espressione più visibile del proprio lavoro: il Comitato è attivo tutto l&#39;anno con iniziative culturali, formative e di prevenzione, organizzate attuando un dialogo continuo con le realtà del territorio.</p>
      <p className={subtitleClassName}>Dal Pride alle politiche pubbliche: tre progetti per una Brescia che preveda tutte le persone</p>
      <p className={textClassName}>Negli ultimi anni il rapporto tra il Comune di Brescia e Brescia Pride si è consolidato attraverso la partecipazione istituzionale alla manifestazione e il dialogo costruito in diversi contesti cittadini. Il Comitato ritiene che esistano oggi le condizioni per compiere un passo ulteriore: trasformare questa vicinanza in un percorso di lavoro condiviso, capace di generare politiche pubbliche che migliorino la qualità della vita dell&apos;intera cittadinanza.</p><p className={textClassName}>I tre progetti proposti riguardano l&#39;attuazione della <b>Carriera Alias</b> nel Comune di Brescia, già prevista dal <em>Gender Equality Plan</em> dell&#39;Amministrazione, la costruzione di un <b>catalogo comunale di percorsi di educazione socio-emotiva</b> che il Comune possa mettere a disposizione delle scuole interessate, e l&#39;avvio di una co progettazione per uno <b>spazio civico stabile</b> dedicato alla comunità LGBTQIA+. Su ciascuno di questi fronti il Comitato mette a disposizione le competenze e le relazioni della rete associativa, con l&#39;obiettivo di arrivare a interventi realizzabili e duraturi.</p>
      <p className={textClassName}><em>«Il Pride è la giornata in cui istituzioni, Comunità e cittadinanza si incontrano, ma i diritti si misurano nei servizi e nelle politiche, e devono funzionare tutto l&apos;anno. Per questo chiediamo all&apos;Amministrazione di condividere un metodo di lavoro con referenti politici e tecnici, tavoli dedicati e un cronoprogramma, in modo tale da poter contribuire attivamente e concretamente nella realizzazione di progetti virtuosi per l&apos;intera cittadinanza. Da parte nostra mettiamo a disposizione competenze, capacità di progettazione e le relazioni costruite in anni di lavoro sul territorio»</em>, afferma <b>Greta Tosoni,</b> Presidente del Comitato Brescia Pride ETS.</p>
      <p className={textClassName}>Il Comitato è già in dialogo con numerose realtà del territorio sugli obiettivi individuati e intende agire come <b>soggetto di mediazione</b> tra istituzioni, società civile e terzo settore. Associazioni storiche, realtà sindacali, collettivi, servizi sanitari, l&apos;Università degli Studi di Brescia e le amministrazioni comunali che sostengono la manifestazione compongono una rete che il Pride vuole ampliare, rendendo le istituzioni partecipi dell&apos;operato associativo e coinvolgendo nuovi soggetti in un lavoro comune.</p><p className={textClassName}>Il Brescia Pride 2026 è patrocinato dal <b>Comune di Brescia</b>, che sostiene la manifestazione anche con la fornitura di materiale economale, dal <b>Comune di Cellatica</b>, che ha contribuito con una donazione a favore della manifestazione, e dai <b>Comuni di Borgosatollo, Collebeato, Malegno, Ome, Provaglio d&apos;Iseo.</b> </p>
      <p className={subtitleClassName}>La giornata del 5 settembre</p>
      <p className={textClassName}>A partire dalle <b>ore 12:00,</b> Campo Marte ospita la settima edizione, con spazi dedicati a 34 associazioni e realtà bresciane. Saranno inoltre presenti un <b>queer market</b> di autoproduzioni e hobbistica di persone della Comunità, un&apos;area <b>food &amp; drink</b> interamente vegana, l&apos;<b>Area Bimbx</b> con spazi e intrattenimento per le persone più piccole - in collaborazione con <b>Siamo Gatti</b> - e le postazioni Trucca Queer e Trucca Bimbx.</p><p className={textClassName}>Uno spazio centrale è riservato all&apos;<b>Area Salute &amp; Prevenzione</b>, con la zona vaccinazioni di <b>ASST Spedali Civili di Brescia</b> - dove sarà possibile vaccinarsi gratuitamente contro l&apos;HPV e ricevere le altre vaccinazioni previste dal piano regionale - la zona informativa sulla salute sessuale a cura di <b>Brescia Checkpoint</b> e l&apos;area di riduzione del danno con il progetto <em>SafeTrip</em> della cooperativa <b>Il Calabrone</b>.</p><p className={textClassName}>Alle <b>14:30</b> cominceranno i primi interventi e le performance dal palco, mentre alle <b>15:30</b> partirà il <b>corteo</b> attraverso le vie cittadine, che rientrerà a Campo Marte verso le <b>17:30</b>. Il Parco Pride resterà attivo anche durante la marcia, per consentire la partecipazione a chi non può o non desidera prendervi parte. Dalle <b>18:00</b> la manifestazione prosegue con interventi dal palco, performance e musica, fino alla chiusura prevista per le <b>20:30</b>.</p><p className={textClassName}>Il corteo sarà attraversato da diversi carri, teatro di intrattenimento e rivendicazione, e vedrà la presenza di una <b>Zona Bianca</b> di decompressione accompagnata da persone volontarie opportunamente formate. Le persone volontarie hanno risposto alla open call lanciata dal Comitato Brescia Pride e alla collaborazione attivata con Volontari per Brescia.</p>
      <p className={textClassName}>Anche a Campo Marte sarà predisposta una <b>Zona Bianca a bassa stimolazione sensoriale</b>, spazi ad alta visibilità per seguire da vicino il palco e sedute per chi ne avrà necessità. Gli interventi saranno inoltre accompagnati dal servizio di <b>interpretariato LIS</b>.</p><p className={textClassName}>L&apos;area di Campo Marte verrà allestita con un <b>palco e relativa rampa completamente accessibili</b> alle persone con mobilità ridotta, spesa sostenuta interamente con l&apos;autofinanziamento. Inoltre, è stato richiesto al <b>Settore Verde Pubblico</b> di adeguare una parte di sentiero in ghiaia per garantire una migliore accessibilità: una soluzione che renderà Campo Marte uno spazio pubblico ancora più accessibile all&apos;intera cittadinanza, non solo durante il Pride.</p>
      <p className={textClassName}>Il Comitato rinnova, come per ogni edizione, il proprio impegno verso la <b>sostenibilità ambientale</b>, invitando le persone partecipanti a utilizzare borracce ai punti acqua, bicchieri riutilizzabili ai punti bar e a usufruire degli <b>Eco Point</b> per la raccolta differenziata. Sul sito web e sui canali social ufficiali verranno pubblicati il percorso del corteo e la mappa dei servizi, con informazioni più approfondite su accessibilità, mobilità sostenibile e logistica. </p>
      <p className={subtitleClassName}>A proposito di Brescia Pride</p>
      <p className={textClassName}>Il Comitato Brescia Pride ETS è una realtà autogestita e indipendente, composta da persone che si impegnano per il riconoscimento e la tutela dei diritti delle persone LGBTQIA+ nel territorio bresciano. Transfemminista, queer, intersezionale, laico, antifascista, antirazzista, autofinanziato e attento alla sostenibilità sociale e ambientale, il Comitato organizza l&apos;omonima manifestazione pubblica annuale e numerose iniziative culturali, educative e sociali durante tutto l&apos;anno, valorizzando la rete di realtà, collettivi ed enti alleati e contribuendo alla costruzione di una società più giusta, laica e plurale. Il progetto si fonda su valori di autodeterminazione, antidiscriminazione e giustizia sociale, ed è aperto alla partecipazione di chiunque condivida questi principi.</p>
      <p className={subtitleClassName}>Per ulteriori informazioni e contatti stampa</p>
      <p className={textClassName}><b>Elisa Belussi, she/they</b></p>
      <p className={textClassName}><a href="mailto:ufficiostampa@bresciapride.it" className="underline text-blue">ufficiostampa@bresciapride.it</a> - <a href="mailto:info@bresciapride.it" className="underline text-blue">info@bresciapride.it</a>
      </p>
      <p className={textClassName}>      <em>Materiali fotografici, logo e mappa dei servizi disponibili su richiesta.</em>
      </p>

      {/* <p className={textClassName}>
        <em>Carriera Alias in Comune, un catalogo di percorsi educativi per le scuole e uno spazio civico per la comunità LGBTQIA+: dialogo già aperto con la Sindaca.</em> <em>La settima edizione si terrà a Campo Marte, con corteo dalle 15:30.</em>
      </p>
      <p className={textClassName}>
        <b>BRESCIA, 1 settembre 2026 - Brescia Pride</b> torna in piazza sabato <b>5 settembre</b> con la sua <b>settima edizione</b>: una giornata di iniziative nel <b>Parco</b> <b>Campo Marte</b> e un corteo attraverso le vie cittadine, sotto lo slogan <b>«Esistiamo ovunque, resistiamo unit3»</b>. Il Comitato sceglie di accompagnare la manifestazione con un annuncio che guarda oltre la singola giornata: la proposta, già presentata alla Sindaca Laura Castelletti, di avviare con il Comune di Brescia un percorso stabile di collaborazione su tre priorità concrete per la città.
      </p>
      <p className={textClassName}>In un momento in cui, in Italia e in Europa, i diritti delle persone LGBTQIA+ sono costantemente rimessi in discussione nel dibattito pubblico e nelle scelte politiche, il Pride bresciano riafferma la propria <b>identità intersezionale, transfemminista, antirazzista e antifascista</b>, ribadendo che il corteo è solo l&apos;espressione più visibile del proprio lavoro: il Comitato è attivo tutto l&#39;anno con iniziative culturali, formative e di prevenzione, organizzate attuando un dialogo continuo con le realtà del territorio.</p>
      <p className={subtitleClassName}>Dal Pride alle politiche pubbliche: tre progetti per una Brescia che preveda tutte le persone</p>
      <p className={textClassName}>Negli ultimi anni il rapporto tra il Comune di Brescia e Brescia Pride si è consolidato attraverso la partecipazione istituzionale alla manifestazione e il dialogo costruito in diversi contesti cittadini. Il Comitato ritiene che esistano oggi le condizioni per compiere un passo ulteriore: trasformare questa vicinanza in un percorso di lavoro condiviso, capace di generare politiche pubbliche che migliorino la qualità della vita dell&apos;intera cittadinanza. I tre progetti proposti riguardano l&#39;attuazione della <b>Carriera Alias</b> nel Comune di Brescia, già prevista dal <em>Gender Equality Plan</em> dell&#39;Amministrazione, la costruzione di un <b>catalogo comunale di percorsi di educazione socio-emotiva</b> che il Comune possa mettere a disposizione delle scuole interessate, e l&#39;avvio di una co progettazione per uno <b>spazio civico stabile</b> dedicato alla comunità LGBTQIA+. Su ciascuno di questi fronti il Comitato mette a disposizione le competenze e le relazioni della rete associativa, con l&#39;obiettivo di arrivare a interventi realizzabili e duraturi.</p>
      <p className={textClassName}><em>«Il Pride è la giornata in cui istituzioni, Comunità e cittadinanza si incontrano, ma i diritti si misurano nei servizi e nelle politiche, e devono funzionare tutto l&apos;anno. Per questo chiediamo all&apos;Amministrazione di condividere un metodo di lavoro con referenti politici e tecnici, tavoli dedicati e un cronoprogramma, in modo tale da poter contribuire attivamente e concretamente nella realizzazione di progetti virtuosi per l&apos;intera cittadinanza. Da parte nostra mettiamo a disposizione competenze, capacità di progettazione e le relazioni costruite in anni di lavoro sul territorio»</em>, afferma <b>Greta Tosoni,</b> Presidente del Comitato Brescia Pride ETS.</p>
      <p className={textClassName}>Il Comitato è già in dialogo con numerose realtà del territorio sugli obiettivi individuati e intende agire come <b>soggetto di mediazione</b> tra istituzioni, società civile e terzo settore. Associazioni storiche, realtà sindacali, collettivi, servizi sanitari, l&apos;Università degli Studi di Brescia e le amministrazioni comunali che sostengono la manifestazione compongono una rete che il Pride vuole ampliare, rendendo le istituzioni partecipi dell&apos;operato associativo e coinvolgendo nuovi soggetti in un lavoro comune. Il Brescia Pride 2026 è patrocinato dal <b>Comune di Brescia</b>, che sostiene la manifestazione anche con la fornitura di materiale economale, e dal <b>Comune di Cellatica</b>, che ha contribuito con una donazione a favore della manifestazione.</p>
      <p className={subtitleClassName}>La giornata del 5 settembre</p>
      <p className={textClassName}>A partire dalle <b>ore 12:00</b> Campo Marte ospita la settima edizione, con spazi dedicati a diverse associazioni e realtà bresciane. Saranno inoltre presenti un <b>queer market</b> di autoproduzioni e artigianato di persone della Comunità, un&apos;area <b>food &amp; drink</b> interamente vegana, l&apos;<b>Area Bimbx</b> con spazi e intrattenimento per le persone più piccole - in collaborazione con <b>Siamo Gatti</b> - e le postazioni Trucca Queer e Trucca Bimbx. Uno spazio centrale è riservato all&apos;<b>Area Salute &amp; Prevenzione</b>, con la zona vaccinazioni di <b>ASST Spedali Civili di Brescia</b> - dove sarà possibile vaccinarsi gratuitamente contro l&apos;HPV e ricevere le altre vaccinazioni previste dal piano regionale - la zona informativa sulla salute sessuale a cura di <b>Brescia Checkpoint</b> e l&apos;area di riduzione del danno con il progetto <em>SafeTrip</em> della cooperativa <b>Il Calabrone</b>. Alle <b>14:30</b> cominceranno i primi interventi e le performance dal palco, mentre alle <b>15:30</b> partirà il <b>corteo</b> attraverso le vie cittadine, che rientrerà a Campo Marte verso le <b>17:30</b>. Il Parco Pride resterà attivo anche durante la marcia, per consentire la partecipazione a chi non può o non desidera prendervi parte. Dalle <b>18:00</b> la manifestazione prosegue con interventi dal palco, performance e musica, fino alla chiusura prevista per le <b>21:00</b>. Il corteo sarà attraversato da diversi carri, teatro di intrattenimento e rivendicazione, e vedrà la presenza di una <b>Zona Bianca</b> di decompressione accompagnata da persone volontarie opportunamente formate.  Le persone volontarie hanno risposto alla open call lanciata dal Comitato Brescia Pride e alla collaborazione attivata con Volontari per Brescia.</p>
      <p className={textClassName}>Anche a Campo Marte sarà predisposta una <b>Zona Bianca a bassa stimolazione sensoriale</b>, spazi ad alta visibilità per seguire da vicino il palco e sedute per chi ne avrà necessità. Gli interventi saranno inoltre accompagnati dal servizio di <b>interpretariato LIS</b>. L&apos;area di Campo Marte verrà allestita con un <b>palco e relativa rampa completamente accessibili</b> alle persone con mobilità ridotta, spesa sostenuta interamente con l&apos;autofinanziamento. Inoltre, è stato richiesto al <b>Settore Verde Pubblico</b> di adeguare una parte di sentiero in ghiaia per garantire una migliore accessibilità: una soluzione che renderà Campo Marte uno spazio pubblico ancora più accessibile all&apos;intera cittadinanza, non solo durante il Pride.</p>
      <p className={textClassName}>Il Comitato rinnova, come per ogni edizione, il proprio impegno verso la <b>sostenibilità ambientale</b>, invitando le persone partecipanti a utilizzare borracce ai punti acqua, bicchieri riutilizzabili ai punti bar e a usufruire degli <b>Eco Point</b> per la raccolta differenziata. Sul sito web e sui canali social ufficiali verranno pubblicati il percorso del corteo e la mappa dei servizi, con informazioni più approfondite su accessibilità, mobilità sostenibile e logistica. </p>
      <p className={subtitleClassName}>A proposito di Brescia Pride</p>
      <p className={textClassName}>Il Comitato Brescia Pride ETS è una realtà autogestita e indipendente, composta da persone che si impegnano per il riconoscimento e la tutela dei diritti delle persone LGBTQIA+ nel territorio bresciano. Transfemminista, queer, intersezionale, laico, antifascista, antirazzista, autofinanziato e attento alla sostenibilità sociale e ambientale, il Comitato organizza l&apos;omonima manifestazione pubblica annuale e numerose iniziative culturali, educative e sociali durante tutto l&apos;anno, valorizzando la rete di realtà, collettivi ed enti alleati e contribuendo alla costruzione di una società più giusta, laica e plurale. Il progetto si fonda su valori di autodeterminazione, antidiscriminazione e giustizia sociale, ed è aperto alla partecipazione di chiunque condivida questi principi.</p> */}
    </div>
  );

  return (
    <TextPage title={title} subtitle={subtitle} textColor={mainColor} bgColor={secondaryColor}>
      {content}
    </TextPage>
  );
}
